apiVersion: v1
kind: Pod
metadata:
  name: image-loader
  namespace: telecom-crm
spec:
  containers:
    - name: loader
      image: docker:24-cli
      command: ["sleep", "3600"]
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  restartPolicy: Never
