apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: telecom-crm
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: telecom-crm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: customer-service
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
