spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KaanKayaS/teleco-crm-microservices.git
          default-label: main             # Okunacak branch
          search-paths: microservices/configs/{application}  # Her servis kendi klasöründen okunur
          clone-on-start: true            # Başlangıçta repo'yu klonla
          timeout: 10                     # Bağlantı zaman aşımı (saniye)
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}

server:
  port: 8881                          # Config Server standart portu

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
