spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/telcox-realm
          jwk-set-uri: http://localhost:8080/realms/telcox-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**

server:
  port: 8080

